name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -qq -y curl ca-certificates bison libopts25 libselinux1-dev autogen m4 autoconf help2man libopts25-dev flex libfont-freetype-perl automake autotools-dev libfreetype6-dev texinfo autopoint libfuse-dev libdevmapper-dev make --no-install-recommends
      - name: Prepare build
        run: |
          mkdir /tmp/grub
          curl https://alpha.gnu.org/gnu/grub/grub-2.04~rc1.tar.gz --output /tmp/grub.tar.gz
          tar -xzf /tmp/grub.tar.gz --strip-components=1 -C /tmp/grub
      - name: Build
        run: |
          cd /tmp/grub
          ./autogen.sh
          ./configure --with-platform=efi --target=i386 --disable-werror
          make
          sudo make install
          /usr/local/bin/grub-mknetdir -d /usr/local/lib/grub/i386-efi --net-directory=/tmp
